name: Consultar Cliente

on:
  push:
    branches: ["main"]
    paths:
      - "clientes/**"
  workflow_dispatch:

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Notificacion
        run: echo "Consulta de cliente realizada. Notificacion del Equipo de AXA."

      
