name: Nuevo CLiente

 on:
  push:
    branches: ["main"]
    paths:
      - "clientes/**"
  workflow_dispatch:

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      -name: Notificacion
      run: echo"Se ha creado un nuevo cliente. Notificacion de el equipo de AXA"
    
    
