name: Actualizar CLiente

 on:
  push:
    branches: ["main"]
    paths:
      - "main.py"
  workflow_dispatch:

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      -name: Notificacion
      run: echo "Cliente recurrente actualizado Notificacion de el equipo de AXA"
    
